# Generated by Django 4.2.30 on 2026-09-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dietary_regime',
            new_name='DietaryRegime',
        ),
    ]
