# Generated by Django 4.2.30 on 2026-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_rename_dietary_regime_dietaryregime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryregime',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
