# Generated by Django 4.2.30 on 2026-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dietaryregime_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=125)),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='season',
        ),
        migrations.AddField(
            model_name='dish',
            name='colors',
            field=models.ManyToManyField(blank=True, to='dishes.color'),
        ),
        migrations.AddField(
            model_name='dish',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='dishes.season'),
        ),
    ]
