# Generated by Django 4.2.30 on 2026-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_season_remove_dish_color_remove_dish_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
