# Generated by Django 4.2.30 on 2026-09-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_color_hex_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='dishes.dish'),
        ),
    ]
