# Generated by Django 4.2.30 on 2026-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_alter_dishingredient_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type_ingredient',
            field=models.CharField(blank=True, choices=[('Spice', 'Epice'), ('Sauce', 'Sauce'), ('Vegetable', 'Légume'), ('Cereal', 'Céréal'), ('Protein', 'Protéine')], max_length=25),
        ),
    ]
